begin;

create table if not exists public.catalog_state (
  id smallint primary key check (id = 1),
  catalog jsonb not null,
  version bigint not null default 1,
  updated_at timestamptz not null default now()
);

create table if not exists public.product_costs (
  product_id text primary key,
  costs jsonb not null check (jsonb_typeof(costs) = 'array'),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_sales (
  id uuid primary key,
  order_number bigint generated by default as identity unique,
  created_at timestamptz not null default now(),
  business_date date not null default ((timezone('America/Cancun', now()))::date),
  created_by text not null,
  confirmed_by text,
  customer text not null default '',
  note text not null default '',
  items jsonb not null check (jsonb_typeof(items) = 'array'),
  subtotal integer not null check (subtotal >= 0),
  total integer not null check (total >= 0),
  cost integer not null check (cost >= 0),
  payment_method text not null check (payment_method in ('Efectivo', 'Transferencia')),
  payment_status text not null check (payment_status in ('Pagado', 'Pendiente')),
  received integer not null check (received >= 0),
  change integer not null check (change >= 0),
  confirmed_at timestamptz
);

create index if not exists admin_sales_business_date_idx
  on public.admin_sales (business_date, created_at desc);

create table if not exists public.auth_attempts (
  attempt_key text primary key,
  attempts integer not null check (attempts >= 0),
  reset_at timestamptz not null
);

alter table public.catalog_state enable row level security;
alter table public.product_costs enable row level security;
alter table public.admin_sales enable row level security;
alter table public.auth_attempts enable row level security;

revoke all on table public.catalog_state from anon, authenticated;
revoke all on table public.product_costs from anon, authenticated;
revoke all on table public.admin_sales from anon, authenticated;
revoke all on table public.auth_attempts from anon, authenticated;

grant select, insert, update, delete on table public.catalog_state to service_role;
grant select, insert, update, delete on table public.product_costs to service_role;
grant select, insert, update, delete on table public.admin_sales to service_role;
grant select, insert, update, delete on table public.auth_attempts to service_role;
grant usage, select on sequence public.admin_sales_order_number_seq to service_role;

insert into public.catalog_state (id, catalog)
values (
  1,
  '{"products":[{"id":"latte","name":"Latte de la casa","category":"Cafés","description":"Espresso, leche cremosa y una pausa que sabe bien. Frío o caliente, a tu manera.","prices":[5500,7000,8500],"active":true,"tone":"coffee"},{"id":"matcha","name":"Matcha latte","category":"Matcha","description":"Un momento de calma. Matcha y leche en una mezcla suave y delicada.","prices":[5000,10000,15000],"active":true,"tone":"matcha"},{"id":"boba","name":"Boba latte","category":"Bobas","description":"Leche, café y perlas de tapioca. Pequeños momentos de felicidad.","prices":[6500,8500,10000],"active":true,"tone":"boba"},{"id":"caramel","name":"Caramel latte","category":"Cafés","description":"Café con leche y un toque de caramelo para endulzar tu día.","prices":[6000,8000,9500],"active":true,"tone":"caramel"},{"id":"frappe","name":"Frappé de chocolate","category":"Frappés","description":"Chocolate, hielo y una textura deliciosamente cremosa.","prices":[6000,8000,9500],"active":true,"tone":"cocoa"},{"id":"americano","name":"Americano","category":"Cafés","description":"El carácter del espresso, con el espacio para disfrutarlo despacio.","prices":[3500,4500,5500],"active":true,"tone":"dark"}],"settings":{"phones":["529841651702","529831137618"],"address":"","hours":"","sample":true},"modifiers":[]}'::jsonb
)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images',
  'product-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

commit;
